In [1]:
from transformers import BertModel, BertConfig, BertTokenizer, AutoTokenizer, AutoModel
import torch

In [2]:
configuration = BertConfig()
model = BertModel(configuration)

In [3]:
pre_model = BertModel.from_pretrained('bert-base-uncased')

In [4]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

In [5]:

input_ids = torch.tensor(tokenizer.encode("Hello, my dog is cute", add_special_tokens=True)).unsqueeze(0)  # Batch size 1
outputs = model(input_ids)

last_hidden_states = outputs[0] 

In [6]:
tokenizer.encode("Hello, my dog is so cute", add_special_tokens=True)

[101, 7592, 1010, 2026, 3899, 2003, 2061, 10140, 102]

In [7]:
outputs[1]

tensor([[ 0.5025, -0.1066, -0.3193, -0.0224,  0.2377, -0.1096, -0.1556, -0.4427,
         -0.7453,  0.6484, -0.2151, -0.5418,  0.1932, -0.3766, -0.5337, -0.3053,
         -0.1505,  0.1740,  0.3818,  0.4940,  0.7192, -0.5849, -0.3827, -0.6587,
          0.3873,  0.5305,  0.4161, -0.2474, -0.7797, -0.8868, -0.5061, -0.0550,
         -0.1582, -0.0809,  0.0516,  0.5210, -0.2199,  0.0162,  0.1671,  0.0383,
         -0.0408, -0.8552,  0.5406,  0.2339,  0.0936,  0.0948,  0.1908, -0.7603,
         -0.1467,  0.6413,  0.0471, -0.1197, -0.9346, -0.1081,  0.2167,  0.3350,
          0.0515, -0.3632,  0.0271, -0.2975, -0.5438, -0.0209,  0.0466,  0.2954,
         -0.7145,  0.0689, -0.2256, -0.1599,  0.0496,  0.7042, -0.5023,  0.5669,
          0.2233,  0.3120,  0.4905,  0.8565, -0.2951, -0.5657,  0.5106,  0.3748,
          0.3425, -0.6396,  0.5265,  0.3933, -0.4516,  0.6099, -0.0763, -0.3290,
          0.2866,  0.1295, -0.0247,  0.5400, -0.7799, -0.2228,  0.4091,  0.2648,
          0.3585, -0.4347, -

In [8]:
tokenizer = AutoTokenizer.from_pretrained("neuralmind/bert-base-portuguese-cased")

In [9]:
model = AutoModel.from_pretrained('neuralmind/bert-base-portuguese-cased')

In [10]:
tokenizer.encode("Oi cachorro", add_special_tokens=True)

[101, 231, 22283, 21809, 102]

In [11]:
input_ids = torch.tensor(tokenizer.encode("Oi cachorro", add_special_tokens=True)).unsqueeze(0)  # Batch size 1
model(input_ids)

(tensor([[[ 0.4391,  0.2382,  0.4776,  ..., -0.6487, -0.2942, -0.2240],
          [ 0.1423, -0.2394,  0.7315,  ..., -0.3250, -0.3804, -0.4942],
          [ 0.0179,  0.0057,  0.6657,  ..., -0.2022, -0.3635, -0.3688],
          [ 0.1560, -0.2160,  0.8530,  ..., -0.4866, -0.4802, -0.0826],
          [ 0.4403,  0.2420,  0.4855,  ..., -0.6434, -0.2925, -0.2182]]],
        grad_fn=<NativeLayerNormBackward>),
 tensor([[ 1.0989e-02, -9.2998e-02, -9.5801e-02,  4.9120e-02, -3.1388e-02,
           1.0846e-01,  9.9885e-01, -7.2293e-02, -5.0860e-02, -1.9239e-02,
          -7.9298e-01, -9.6920e-03, -1.2799e-01, -2.9235e-02,  9.5859e-02,
           7.6287e-03, -2.7892e-02, -1.1119e-02,  9.0019e-01,  9.7571e-01,
          -7.8681e-02,  5.1344e-03,  1.1104e-01,  3.8843e-02, -2.2465e-02,
          -6.7953e-02,  1.6606e-01, -8.0387e-02, -8.5611e-02, -9.3729e-03,
           4.6322e-02, -9.8558e-01, -9.2037e-01, -9.1726e-05, -4.1719e-02,
          -2.2570e-02, -1.1078e-01,  8.2394e-03,  8.3357e-01,  1.8273

# Using API

In [14]:
from bert_serving.client import BertClient
bc = BertClient()


array([[ 0.12984075,  0.2268846 , -0.16972512, ...,  0.22794035,
         0.20376413,  0.16759966]], dtype=float32)

In [32]:
rei = bc.encode(["rei"])

In [33]:
homem = bc.encode(["homem"])

In [34]:
mulher = bc.encode(["mulher"])

In [35]:
rainha = bc.encode(["rainha"])

In [36]:
rei - homem + mulher

array([[-0.10123543,  0.19268402, -0.3761071 , ...,  0.04156766,
         0.06547127, -0.21731567]], dtype=float32)

In [37]:
rainha

array([[ 0.06416215,  0.05139285,  0.06549106, ..., -0.09644315,
         0.02544508,  0.02801553]], dtype=float32)

In [38]:
from torch.nn import CosineSimilarity

In [39]:
cos = CosineSimilarity(dim=1, eps=1e-6)

In [41]:
cos(torch.from_numpy(rainha), torch.from_numpy(rei - homem + mulher))

tensor([0.8058])

In [42]:
cos(torch.from_numpy(rainha), torch.from_numpy(rei))

tensor([0.8086])

## Now with multi

In [43]:
king = bc.encode(["king"])

In [44]:
queen = bc.encode(["queen"])

In [45]:
woman = bc.encode(["woman"])

In [46]:
man = bc.encode(["man"])

In [47]:
cos(torch.from_numpy(queen), torch.from_numpy(king - man + woman))

tensor([0.8885])

In [48]:
cos(torch.from_numpy(queen), torch.from_numpy(king))

tensor([0.9634])